import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class AkunBaruBeratBadanStLbScreen extends StatelessWidget {const AkunBaruBeratBadanStLbScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 33.h, vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 7.h), child: RichText(text: TextSpan(children: [TextSpan(text: "How much do you ", style: CustomTextStyles.headlineSmallff000000_1), TextSpan(text: "weight?", style: CustomTextStyles.headlineSmallff000000)]), textAlign: TextAlign.left)), SizedBox(height: 43.v), CustomImageView(imagePath: ImageConstant.imgCuriosityPeopleRafiki, height: 202.adaptSize, width: 202.adaptSize, alignment: Alignment.center), SizedBox(height: 49.v), Padding(padding: EdgeInsets.only(left: 41.h), child: Row(children: [_buildFrameSeventeen(context, dynamicText: "st"), Padding(padding: EdgeInsets.only(left: 27.h), child: _buildFrameSeventeen(context, dynamicText: "lb"))])), SizedBox(height: 25.v), Container(height: 28.v, width: 201.h, margin: EdgeInsets.only(left: 41.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Container(width: 67.h, padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 5.v), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL50), child: Text("kg", style: CustomTextStyles.labelLargeErrorContainer))), Align(alignment: Alignment.center, child: Container(width: 68.h, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 6.v), decoration: AppDecoration.outlineOnPrimaryContainer, child: Text("lb", style: CustomTextStyles.labelLargeErrorContainer))), Align(alignment: Alignment.centerRight, child: Container(width: 68.h, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 6.v), decoration: AppDecoration.outlineOnPrimaryContainer1.copyWith(borderRadius: BorderRadiusStyle.customBorderLR50), child: Text("st & lb", style: CustomTextStyles.labelLargeWhiteA700)))])), Spacer(flex: 49), CustomOutlinedButton(text: "Next", margin: EdgeInsets.only(left: 7.h, right: 25.h), onPressed: () {onTapNext(context);}), Spacer(flex: 50)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 39.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 15.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 4, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.onPrimaryContainer, dotHeight: 8.v, dotWidth: 8.h)))); } 
/// Common widget
Widget _buildFrameSeventeen(BuildContext context, {required String dynamicText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Text(dynamicText, style: CustomTextStyles.labelLargeBlack900.copyWith(color: appTheme.black900))), SizedBox(height: 2.v), SizedBox(width: 73.h, child: Divider(color: appTheme.teal100))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the akunBaruTinggiBadanCmScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.akunBaruTinggiBadanCmScreen); } 
 }
