import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/custom_elevated_button.dart';import 'package:fery_s_application2/widgets/custom_icon_button.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:fery_s_application2/presentation/halaman_profile_edit_tinggi_inch_bottomsheet/halaman_profile_edit_tinggi_inch_bottomsheet.dart';class HalamanProfileEditTinggiCmBottomsheet extends StatelessWidget {const HalamanProfileEditTinggiCmBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return _buildScrollView(context); } 
/// Section Widget
Widget _buildScrollView(BuildContext context) { return SingleChildScrollView(child: Container(padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 7.v), decoration: AppDecoration.fillWhiteA70001.copyWith(borderRadius: BorderRadiusStyle.customBorderTL14), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 33.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 4.v), child: Text("Tinggi", style: CustomTextStyles.titleMediumPrimaryContainer)), Spacer(), Container(height: 16.v, width: 75.h, margin: EdgeInsets.only(top: 5.v, bottom: 2.v), child: Stack(alignment: Alignment.centerRight, children: [CustomOutlinedButton(height: 16.v, width: 38.h, text: "cm", buttonStyle: CustomButtonStyles.outlineOnPrimaryContainerTL50, buttonTextStyle: CustomTextStyles.robotoFlexWhiteA700, alignment: Alignment.centerLeft), CustomOutlinedButton(height: 16.v, width: 38.h, text: "inch", buttonStyle: CustomButtonStyles.outlineOnPrimaryContainerLR501, buttonTextStyle: CustomTextStyles.robotoFlexErrorContainer, onPressed: () {onTapInch(context);}, alignment: Alignment.centerRight)])), Padding(padding: EdgeInsets.only(left: 30.h), child: CustomIconButton(height: 23.adaptSize, width: 23.adaptSize, padding: EdgeInsets.all(1.h), onTap: () {onTapBtnCancel(context);}, child: CustomImageView(imagePath: ImageConstant.imgCancel)))])), SizedBox(height: 82.v), Padding(padding: EdgeInsets.only(right: 132.h), child: Text("cm", style: theme.textTheme.labelSmall)), SizedBox(height: 4.v), Align(alignment: Alignment.centerLeft, child: SizedBox(width: 197.h, child: Divider(indent: 132.h))), SizedBox(height: 75.v), CustomElevatedButton(width: 213.h, text: "SIMPAN", onPressed: () {onTapSIMPAN(context);}, alignment: Alignment.center), SizedBox(height: 16.v)]))); } 

/// Shows a modal bottom sheet with [HalamanProfileEditTinggiInchBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapInch(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>HalamanProfileEditTinggiInchBottomsheet(),isScrollControlled: true); } 
/// Navigates to the halamanProfileEditScreen when the action is triggered.
onTapBtnCancel(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanProfileEditScreen); } 
/// Navigates to the halamanProfileEditScreen when the action is triggered.
onTapSIMPAN(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanProfileEditScreen); } 
 }
