import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:fery_s_application2/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class MasukScreen extends StatelessWidget {MasukScreen({Key? key}) : super(key: key);

TextEditingController userNameController = TextEditingController();

TextEditingController passwordController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 54.v), child: Column(children: [SizedBox(height: 85.v, width: 135.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 15.h), child: Text("Sign In", style: CustomTextStyles.displaySmallRobotoFlexBlack900))), Align(alignment: Alignment.bottomCenter, child: Text("CaloLife", style: theme.textTheme.displaySmall))])), SizedBox(height: 54.v), Padding(padding: EdgeInsets.only(right: 6.h), child: CustomTextFormField(controller: userNameController, hintText: "Email or Username", hintStyle: CustomTextStyles.bodyLargeBluegray400, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.only(right: 25.h, bottom: 14.v), child: CustomImageView(imagePath: ImageConstant.imgEmail, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 38.v), borderDecoration: TextFormFieldStyleHelper.underLineOnPrimaryContainer, filled: false)), SizedBox(height: 36.v), Padding(padding: EdgeInsets.only(right: 5.h), child: CustomTextFormField(controller: passwordController, hintText: "Password", hintStyle: CustomTextStyles.bodyLargeBluegray400, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.only(right: 25.h, bottom: 14.v), child: CustomImageView(imagePath: ImageConstant.imgLock, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 38.v), suffix: Container(margin: EdgeInsets.only(left: 30.h, right: 11.h, bottom: 14.v), child: CustomImageView(imagePath: ImageConstant.imgVisibility, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 38.v), obscureText: true, borderDecoration: TextFormFieldStyleHelper.underLineOnPrimaryContainer, filled: false)), SizedBox(height: 27.v), CustomOutlinedButton(text: "Sign In", margin: EdgeInsets.symmetric(horizontal: 34.h)), SizedBox(height: 23.v), Text("Forgot password?", style: CustomTextStyles.titleMediumPrimary), Spacer(), SizedBox(height: 22.v), GestureDetector(onTap: () {onTapTxtDoesnthavean(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "Doesn't have an account? ", style: CustomTextStyles.bodySmallff676767), TextSpan(text: "Register here", style: CustomTextStyles.labelLargeff01ab6c)]), textAlign: TextAlign.left))]))))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 46.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.fromLTRB(17.h, 16.v, 323.h, 16.v), onTap: () {onTapVector(context);})); } 

/// Navigates back to the previous screen.
onTapVector(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the akunBaruJenisKelaminScreen when the action is triggered.
onTapTxtDoesnthavean(BuildContext context) { Navigator.pushNamed(context, AppRoutes.akunBaruJenisKelaminScreen); } 
 }
