import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/presentation/halaman_bacaan_one_page/halaman_bacaan_one_page.dart';import 'package:fery_s_application2/presentation/halaman_dashboard_page/halaman_dashboard_page.dart';import 'package:fery_s_application2/presentation/halaman_konsultasi_page/halaman_konsultasi_page.dart';import 'package:fery_s_application2/presentation/halaman_profile_page/halaman_profile_page.dart';import 'package:fery_s_application2/widgets/custom_bottom_bar.dart';import 'package:fery_s_application2/widgets/custom_elevated_button.dart';import 'package:fery_s_application2/widgets/custom_search_view.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class HalamanKonsultasiSearchWalterScreen extends StatelessWidget {HalamanKonsultasiSearchWalterScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 11.v), Expanded(child: SingleChildScrollView(child: _buildHalamanKonsultasi(context)))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildHalamanKonsultasi(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(children: [Padding(padding: EdgeInsets.only(left: 44.h, right: 42.h), child: CustomSearchView(controller: searchController, hintText: "walter")), SizedBox(height: 44.v), Container(padding: EdgeInsets.all(10.h), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.circleBorder22), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgPlay48x48, height: 48.adaptSize, width: 48.adaptSize, margin: EdgeInsets.only(top: 1.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Dr. Walter Putih", style: theme.textTheme.labelLarge), SizedBox(height: 2.v), Text("Dentist", style: CustomTextStyles.bodySmallErrorContainer), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 9.v, width: 34.h, text: "7 years", margin: EdgeInsets.only(top: 2.v, bottom: 5.v), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.robotoFlexErrorContainerRegular), CustomElevatedButton(height: 16.v, width: 75.h, text: "Chat", buttonStyle: CustomButtonStyles.fillOnError, buttonTextStyle: CustomTextStyles.bodySmallPrimaryContainer_1, onPressed: () {onTapChat(context);})])])))]))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Homebluegray400: return "/"; case BottomBarEnum.Bookprimary: return AppRoutes.halamanBacaanOnePage; case BottomBarEnum.Navrecipe: return AppRoutes.halamanDashboardPage; case BottomBarEnum.Chat: return AppRoutes.halamanKonsultasiPage; case BottomBarEnum.Mood: return AppRoutes.halamanProfilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.halamanBacaanOnePage: return HalamanBacaanOnePage(); case AppRoutes.halamanDashboardPage: return HalamanDashboardPage(); case AppRoutes.halamanKonsultasiPage: return HalamanKonsultasiPage(); case AppRoutes.halamanProfilePage: return HalamanProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the halamanKonsultasiChatTwoScreen when the action is triggered.
onTapChat(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanKonsultasiChatTwoScreen); } 
 }
