import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class AkunBaruJenisKelaminScreen extends StatelessWidget {const AkunBaruJenisKelaminScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 22.v), child: Column(children: [RichText(text: TextSpan(children: [TextSpan(text: "What’s your ", style: CustomTextStyles.headlineSmallff000000_1), TextSpan(text: "gender?", style: CustomTextStyles.headlineSmallff000000)]), textAlign: TextAlign.left), SizedBox(height: 5.v), CustomImageView(imagePath: ImageConstant.imgGenderIdentityRafiki, height: 254.adaptSize, width: 254.adaptSize, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 20.h)), SizedBox(height: 15.v), _buildFrameEleven(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 41.v, leadingWidth: 39.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 15.h, top: 11.v, bottom: 6.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: Container(height: 8.v, margin: EdgeInsets.only(top: 6.v, bottom: 27.v), child: AnimatedSmoothIndicator(activeIndex: 0, count: 4, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.onPrimaryContainer, dotHeight: 8.v, dotWidth: 8.h)))); } 
/// Section Widget
Widget _buildFrameEleven(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(width: 122.h, text: "Male", leftIcon: Container(margin: EdgeInsets.only(right: 9.h), child: CustomImageView(imagePath: ImageConstant.imgMale, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleMediumRobotoWhiteA700), CustomOutlinedButton(width: 122.h, text: "Female", leftIcon: Container(margin: EdgeInsets.only(right: 3.h), child: CustomImageView(imagePath: ImageConstant.imgFemale, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleMediumRobotoWhiteA700)]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
