import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/custom_elevated_button.dart';import 'package:fery_s_application2/widgets/custom_icon_button.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:fery_s_application2/presentation/halaman_profile_edit_tinggi_cm_bottomsheet/halaman_profile_edit_tinggi_cm_bottomsheet.dart';class HalamanProfileEditTinggiInchBottomsheet extends StatelessWidget {const HalamanProfileEditTinggiInchBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return _buildScrollView(context); } 
/// Section Widget
Widget _buildScrollView(BuildContext context) { return SingleChildScrollView(child: Container(padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 7.v), decoration: AppDecoration.fillWhiteA70001.copyWith(borderRadius: BorderRadiusStyle.customBorderTL14), child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 33.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 4.v), child: Text("Tinggi", style: CustomTextStyles.titleMediumPrimaryContainer)), Spacer(), Container(height: 16.v, width: 75.h, margin: EdgeInsets.only(top: 5.v, bottom: 2.v), child: Stack(alignment: Alignment.centerRight, children: [CustomOutlinedButton(height: 16.v, width: 38.h, text: "cm", buttonStyle: CustomButtonStyles.outlineOnPrimaryContainer, buttonTextStyle: CustomTextStyles.robotoFlexErrorContainer, onPressed: () {onTapCm(context);}, alignment: Alignment.centerLeft), CustomOutlinedButton(height: 16.v, width: 38.h, text: "inch", buttonStyle: CustomButtonStyles.outlineOnPrimaryContainerLR50, buttonTextStyle: CustomTextStyles.robotoFlexWhiteA700Bold, alignment: Alignment.centerRight)])), Padding(padding: EdgeInsets.only(left: 30.h), child: CustomIconButton(height: 23.adaptSize, width: 23.adaptSize, padding: EdgeInsets.all(1.h), onTap: () {onTapBtnCancel(context);}, child: CustomImageView(imagePath: ImageConstant.imgCancel)))]))), SizedBox(height: 81.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Text("feet", style: theme.textTheme.labelSmall)), SizedBox(height: 4.v), SizedBox(width: 65.h, child: Divider())]), Padding(padding: EdgeInsets.only(left: 50.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Text("inch", style: theme.textTheme.labelSmall)), SizedBox(height: 4.v), SizedBox(width: 65.h, child: Divider())]))]), SizedBox(height: 75.v), CustomElevatedButton(width: 213.h, text: "SIMPAN", onPressed: () {onTapSIMPAN(context);}), SizedBox(height: 16.v)]))); } 

/// Shows a modal bottom sheet with [HalamanProfileEditTinggiCmBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapCm(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>HalamanProfileEditTinggiCmBottomsheet(),isScrollControlled: true); } 
/// Navigates to the halamanProfileEditScreen when the action is triggered.
onTapBtnCancel(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanProfileEditScreen); } 
/// Navigates to the halamanProfileEditScreen when the action is triggered.
onTapSIMPAN(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanProfileEditScreen); } 
 }
