import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class HalamanProfileEditNamaScreen extends StatelessWidget {HalamanProfileEditNamaScreen({Key? key}) : super(key: key);

TextEditingController nameController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700.withOpacity(0.95), resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: SizedBox(height: 802.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [_buildProfileInfoSection(context), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 48.h, vertical: 191.v), decoration: AppDecoration.fillBlueGray, child: Container(margin: EdgeInsets.only(right: 7.h), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 11.v), decoration: AppDecoration.fillWhiteA70001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Text("Name", style: theme.textTheme.labelLarge))), SizedBox(height: 8.v), CustomTextFormField(controller: nameController, hintText: "John Doe", hintStyle: CustomTextStyles.bodySmallErrorContainer_1, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 12.v), borderDecoration: TextFormFieldStyleHelper.fillGray, fillColor: appTheme.gray30001), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(right: 2.h), child: Text("0/30", style: CustomTextStyles.robotoFlexGray30001)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(right: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Text("BATAL", style: CustomTextStyles.labelLargeBlueA100), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("OKE", style: CustomTextStyles.labelLargeBlueA200))]))]))))])))))); } 
/// Section Widget
Widget _buildProfileInfoSection(BuildContext context) { return Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 13.h, top: 16.v, right: 28.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgArrowLeft(context);}), Padding(padding: EdgeInsets.only(left: 25.h, top: 3.v), child: Text("Edit profil", style: theme.textTheme.titleMedium))]), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 3.h), child: Row(children: [Padding(padding: EdgeInsets.only(top: 8.v, bottom: 7.v), child: Text("Profile picture", style: theme.textTheme.labelLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgAddAPhoto, height: 31.adaptSize, width: 31.adaptSize), CustomImageView(imagePath: ImageConstant.imgChevronRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 3.v))])), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 4.h), child: _buildUserProfileSection(context, fotoProfil: "Name", fotoProfil1: "John Doe")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 4.h), child: _buildUserProfileSection(context, fotoProfil: "Gender", fotoProfil1: "Male")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 4.h), child: _buildUserProfileSection(context, fotoProfil: "Tinggi", fotoProfil1: "187.3cm")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 4.h), child: _buildUserProfileSection(context, fotoProfil: "Berat", fotoProfil1: "68.8kg"))]))); } 
/// Common widget
Widget _buildUserProfileSection(BuildContext context, {required String fotoProfil, required String fotoProfil1, }) { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.symmetric(vertical: 4.v), child: Text(fotoProfil, style: theme.textTheme.labelLarge!.copyWith(color: theme.colorScheme.primaryContainer))), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 4.v), child: Text(fotoProfil1, style: CustomTextStyles.labelLargePrimary.copyWith(color: theme.colorScheme.primary))), CustomImageView(imagePath: ImageConstant.imgChevronRight, height: 24.adaptSize, width: 24.adaptSize)]); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
