import '../halaman_dashboard_rekomendasi_olahraga_six_screen/widgets/userprofile3_item_widget.dart';import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_subtitle.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class HalamanDashboardRekomendasiOlahragaSixScreen extends StatelessWidget {const HalamanDashboardRekomendasiOlahragaSixScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 26.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(children: [_buildUserProfile(context), SizedBox(height: 10.v), _buildView(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 46.v, leadingWidth: 39.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 15.h, top: 11.v, bottom: 11.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "Calisthenic", margin: EdgeInsets.only(left: 31.h))); } 
/// Section Widget
Widget _buildUserProfile(BuildContext context) { return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 10.v);}, itemCount: 9, itemBuilder: (context, index) {return Userprofile3ItemWidget(onTapUserProfile: () {onTapUserProfile(context);});}); } 
/// Section Widget
Widget _buildView(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 7.h), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 65.v, width: 58.h, margin: EdgeInsets.only(bottom: 6.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 58.adaptSize, width: 58.adaptSize, decoration: BoxDecoration(color: appTheme.tealA100, borderRadius: BorderRadius.circular(12.h)))), CustomImageView(imagePath: ImageConstant.imgGrandSlamBro1, height: 58.adaptSize, width: 58.adaptSize, alignment: Alignment.topCenter)])), Container(width: 123.h, margin: EdgeInsets.only(left: 19.h, top: 27.v, bottom: 24.v), child: RichText(text: TextSpan(children: [TextSpan(text: "Tennis\n", style: CustomTextStyles.bodySmallff26323812), TextSpan(text: "192calories", style: CustomTextStyles.bodySmallff01ab6c12), TextSpan(text: "/30minutes", style: CustomTextStyles.bodySmallff26323812)]), textAlign: TextAlign.left))])); } 
/// Navigates to the halamanDashboardRekomendasiOlahragaFiveScreen when the action is triggered.
onTapUserProfile(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanDashboardRekomendasiOlahragaFiveScreen); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
