import '../halaman_dashboard_rekomendasi_olahraga_two_screen/widgets/userprofile1_item_widget.dart';import '../halaman_dashboard_rekomendasi_olahraga_two_screen/widgets/userprofile2_item_widget.dart';import '../halaman_dashboard_rekomendasi_olahraga_two_screen/widgets/userprofile_item_widget.dart';import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/custom_search_view.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class HalamanDashboardRekomendasiOlahragaTwoScreen extends StatelessWidget {HalamanDashboardRekomendasiOlahragaTwoScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 11.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 39.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildArrowLeftRow(context), SizedBox(height: 89.v), _buildCalisthenicStack(context), SizedBox(height: 24.v), _buildCardioStack(context), SizedBox(height: 24.v), _buildRunTextStack(context)]))))])))); } 
/// Section Widget
Widget _buildArrowLeftRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 15.h, right: 54.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 3.v), onTap: () {onTapImgArrowLeft(context);}), Expanded(child: Padding(padding: EdgeInsets.only(left: 17.h), child: CustomSearchView(controller: searchController, hintText: "Cari olahraga", contentPadding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 6.v))))])); } 
/// Section Widget
Widget _buildCalisthenicStack(BuildContext context) { return SizedBox(height: 196.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomLeft, children: [Padding(padding: EdgeInsets.only(left: 14.h, right: 10.h), child: _buildCardioRow(context, cardioText: "Calisthenic", moreText: "More ", onTapCardioRow: () {onTapCardioRow(context);})), Align(alignment: Alignment.bottomLeft, child: SizedBox(height: 195.v, child: ListView.separated(padding: EdgeInsets.only(top: 61.v, bottom: 21.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: 5, itemBuilder: (context, index) {return UserprofileItemWidget();})))])); } 
/// Section Widget
Widget _buildCardioStack(BuildContext context) { return Container(height: 196.v, width: 348.h, margin: EdgeInsets.only(left: 12.h), child: Stack(alignment: Alignment.bottomRight, children: [Padding(padding: EdgeInsets.only(right: 12.h), child: _buildCardioRow(context, cardioText: "Cardio", moreText: "More ")), Align(alignment: Alignment.bottomRight, child: SizedBox(height: 195.v, child: ListView.separated(padding: EdgeInsets.only(left: 21.h, top: 61.v, bottom: 21.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: 5, itemBuilder: (context, index) {return Userprofile1ItemWidget();})))])); } 
/// Section Widget
Widget _buildRunTextStack(BuildContext context) { return SizedBox(height: 196.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomLeft, child: SizedBox(height: 195.v, child: ListView.separated(padding: EdgeInsets.only(top: 68.v, bottom: 14.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: 4, itemBuilder: (context, index) {return Userprofile2ItemWidget();}))), Padding(padding: EdgeInsets.only(left: 14.h, right: 10.h), child: _buildCardioRow(context, cardioText: "Weightlifting", moreText: "More "))])); } 
/// Common widget
Widget _buildCardioRow(BuildContext context, {required String cardioText, required String moreText, Function? onTapCardioRow, }) { return GestureDetector(onTap: () {onTapCardioRow!.call();}, child: Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 19.v), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.circleBorder22), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 18.h, bottom: 137.v), child: Text(cardioText, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray900))), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 137.v), child: Text(moreText, style: CustomTextStyles.bodySmallBlueA200.copyWith(color: appTheme.blueA200))), CustomImageView(imagePath: ImageConstant.imgChevronRight, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 10.h, top: 3.v, bottom: 140.v))]))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the halamanDashboardRekomendasiOlahragaSixScreen when the action is triggered.
onTapCardioRow(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanDashboardRekomendasiOlahragaSixScreen); } 
 }
