import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class HalamanProfilePage extends StatelessWidget {const HalamanProfilePage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 6.v), child: _buildProfileSection(context))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 38.v, actions: [AppbarTrailingImage(imagePath: ImageConstant.imgVectorBlack900, margin: EdgeInsets.symmetric(horizontal: 14.h, vertical: 9.v))]); } 
/// Section Widget
Widget _buildProfileSection(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(children: [GestureDetector(onTap: () {onTapTwentyThree(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 11.v), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgPlay48x48, height: 36.adaptSize, width: 36.adaptSize, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(left: 31.h, top: 9.v, bottom: 8.v), child: Text("John Doe", style: theme.textTheme.titleMedium))]))), SizedBox(height: 89.v), Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 11.v), decoration: AppDecoration.fillGray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 100.h, margin: EdgeInsets.only(top: 1.v), child: RichText(text: TextSpan(children: [TextSpan(text: "Current ", style: CustomTextStyles.labelLargeff202124), TextSpan(text: "BMI: 23.4", style: CustomTextStyles.labelLargeff202124), TextSpan(text: " "), TextSpan(text: " ", style: CustomTextStyles.bodySmallfffb6c40), TextSpan(text: "Ideal Weight", style: CustomTextStyles.bodySmallff01ab6c)]), textAlign: TextAlign.left)), CustomImageView(imagePath: ImageConstant.imgHelpOutline, height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.only(left: 186.h, bottom: 10.v))]), SizedBox(height: 43.v), SizedBox(height: 11.v, width: 299.h, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgFrame26080033, height: 11.v, width: 299.h, alignment: Alignment.center), Align(alignment: Alignment.topLeft, child: Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 99.h, top: 1.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(4.h), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 0))])))])), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("15", style: CustomTextStyles.bodySmallPrimaryContainer_1), Text("18.5", style: CustomTextStyles.bodySmallPrimaryContainer_1), Text("25", style: CustomTextStyles.bodySmallPrimaryContainer_1), Text("30", style: CustomTextStyles.bodySmallPrimaryContainer_1), Text("35", style: CustomTextStyles.bodySmallPrimaryContainer_1), Text("40", style: CustomTextStyles.bodySmallPrimaryContainer_1)])), SizedBox(height: 12.v)]))])); } 
/// Navigates to the halamanProfileEditScreen when the action is triggered.
onTapTwentyThree(BuildContext context) { Navigator.pushNamed(context, AppRoutes.halamanProfileEditScreen); } 
 }
