import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class AkunBaruTinggiBadanInchScreen extends StatelessWidget {const AkunBaruTinggiBadanInchScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 22.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: RichText(text: TextSpan(children: [TextSpan(text: "How ", style: CustomTextStyles.headlineSmallff000000_1), TextSpan(text: "tall are you?", style: CustomTextStyles.headlineSmallff000000)]), textAlign: TextAlign.left)), SizedBox(height: 51.v), CustomImageView(imagePath: ImageConstant.imgHeightMeterPana, height: 148.adaptSize, width: 148.adaptSize, alignment: Alignment.center), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(left: 84.h), child: Row(children: [Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 13.h), child: Text("8", style: CustomTextStyles.bodyLargeRobotoOnPrimaryContainer))), SizedBox(height: 9.v), _buildDivider(context)]), Padding(padding: EdgeInsets.only(left: 80.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 9.h), child: Text("99", style: CustomTextStyles.bodyLargeRobotoOnPrimaryContainer)), SizedBox(height: 9.v), SizedBox(width: 39.h, child: Divider())]))])), SizedBox(height: 3.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 101.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("3", style: CustomTextStyles.bodyLargeRobotoPrimaryContainer)), Padding(padding: EdgeInsets.only(left: 17.h, bottom: 3.v), child: Text("Feet", style: CustomTextStyles.bodyLargeRobotoTeal100)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: Text("0", style: CustomTextStyles.bodyLargeRobotoBlack900)), Padding(padding: EdgeInsets.only(left: 17.h, bottom: 3.v), child: Text("Inch", style: CustomTextStyles.bodyLargeRobotoTeal100)), CustomImageView(imagePath: ImageConstant.imgArrowDropDown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h))]))), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 84.h), child: Row(children: [_buildDivider(context), SizedBox(width: 119.h, child: Divider(indent: 80.h))])), Padding(padding: EdgeInsets.only(left: 101.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 6.v), child: Text("4", style: CustomTextStyles.bodyLargeRobotoOnPrimaryContainer)), Padding(padding: EdgeInsets.only(left: 109.h, bottom: 6.v), child: Text("1", style: CustomTextStyles.bodyLargeRobotoOnPrimaryContainer))])), Spacer(flex: 57), CustomOutlinedButton(text: "Next", margin: EdgeInsets.only(left: 33.h, right: 51.h), onPressed: () {onTapNext(context);}), Spacer(flex: 42)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 39.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 15.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 4, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.onPrimaryContainer, dotHeight: 8.v, dotWidth: 8.h)))); } 
/// Common widget
Widget _buildDivider(BuildContext context) { return SizedBox(height: 1.v, width: 39.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 39.h, child: Divider())), Align(alignment: Alignment.center, child: SizedBox(width: 39.h, child: Divider()))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the akunBaruBmiScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.akunBaruBmiScreen); } 
 }
