import 'package:fery_s_application2/core/app_export.dart';import 'package:fery_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:fery_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:fery_s_application2/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class AkunBaruTinggiBadanCmScreen extends StatelessWidget {const AkunBaruTinggiBadanCmScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 40.h, vertical: 22.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: RichText(text: TextSpan(children: [TextSpan(text: "How ", style: CustomTextStyles.headlineSmallff000000_1), TextSpan(text: "tall are you?", style: CustomTextStyles.headlineSmallff000000)]), textAlign: TextAlign.left)), SizedBox(height: 51.v), CustomImageView(imagePath: ImageConstant.imgHeightMeterPana, height: 148.adaptSize, width: 148.adaptSize, alignment: Alignment.center), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(left: 51.h, right: 71.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 28.v), child: _buildDividerRow(context)), _buildHeightInput(context, dynamicText: "72")])), SizedBox(height: 3.v), Align(alignment: Alignment.centerRight, child: Container(height: 24.v, width: 194.h, margin: EdgeInsets.only(right: 18.h), child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgArrowDropDown, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerRight, onTap: () {onTapImgArrowDropDown(context);}), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(top: 1.v, right: 23.h, bottom: 1.v), child: Row(children: [Text("1", style: CustomTextStyles.bodyLargeRobotoPrimaryContainer), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("m", style: CustomTextStyles.bodyLargeRobotoTeal100)), Spacer(), _buildHeightInput(context, dynamicText: "73"), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("cm", style: CustomTextStyles.bodyLargeRobotoTeal100))])))]))), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 51.h, right: 71.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildDividerRow(context), SizedBox(width: 39.h, child: Divider())])), Padding(padding: EdgeInsets.only(left: 68.h, right: 82.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 5.v), child: Text("2", style: CustomTextStyles.bodyLargeRobotoOnPrimaryContainer)), Padding(padding: EdgeInsets.only(bottom: 5.v), child: Text("74", style: CustomTextStyles.bodyLargeRobotoOnPrimaryContainer))])), Spacer(flex: 57), CustomOutlinedButton(text: "Next", margin: EdgeInsets.only(right: 18.h), onPressed: () {onTapNext(context);}), Spacer(flex: 42)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 39.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 15.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 4, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.onPrimaryContainer, dotHeight: 8.v, dotWidth: 8.h)))); } 
/// Common widget
Widget _buildHeightInput(BuildContext context, {required String dynamicText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 9.h), child: Text(dynamicText, style: CustomTextStyles.bodyLargeRobotoBlack900.copyWith(color: appTheme.black900))), SizedBox(height: 5.v), SizedBox(width: 39.h, child: Divider())]); } 
/// Common widget
Widget _buildDividerRow(BuildContext context) { return SizedBox(height: 1.v, width: 39.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 39.h, child: Divider())), Align(alignment: Alignment.center, child: SizedBox(width: 39.h, child: Divider()))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the akunBaruTinggiBadanCmOneScreen when the action is triggered.
onTapImgArrowDropDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.akunBaruTinggiBadanCmOneScreen); } 
/// Navigates to the akunBaruBmiScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.akunBaruBmiScreen); } 
 }
